stages:
  - docker
services:
  - docker:dind
docker-job:
  stage: docker
  image: docker:dind
  tags:
    - shh
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t registry.gitlab.com/stas91n/gitlab-ci-cd .
    - docker push registry.gitlab.com/stas91n/gitlab-ci-cd
